name: ELK stack deployment

jobs:
  fetch-infisical-secrets:
    name: Fetching Infisical secrets
    uses: Infisical/secrets-action@v1.0.7
      with:
        client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
        client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
